const articles = [
  {
    name: "internet",
    id: 1,
    title: "Internet",
    content: [
      "How does the internet work?",
      "what is HTTP?",
      "Browsers and how they work?",
      "DNS and how it work",
      "What is Domain Name?",
      "What is hosting?",
    ],
  },
  {
    name: "html",
    id: 2,
    title: "HTML",
    content: [
      "Basics",
      "Forms and Validation",
      "Conventions and Best Practices",
      "Accessibility",
      "SEO Basic",
    ],
  },
  {
    name: "css",
    id: 3,
    title: "CSS",
    content: [
      "Basics",
      "Pseudo-classes",
      "Box model",
      "Flexbox",
      "Grid",
      "Positioning",
      "Units (px,em,rem,vh)",
      "Responsive design and Media Queries",
    ],
  },
  {
    name: "js",
    id: "4",
    title: "JavaScript",
    content: [
      "Syntax and Basic construction",
      "DOM manipulation",
      "Fetch API / Ajax (XHR)",
      "ES6 and modular JavaScript",
      "concepts: hosting, evnet bubbling, scope, prototype, shadow DOM, strict",
    ],
  },
  {
    name: "vcs",
    id: "5",
    title: "Version Control Systems",
    content: [
      "Git - initiate a repository",
      "Git - stage/unstage changes",
      "Git - commit",
      "Git - push",
      "GitHub",
    ],
  },
  {
    name: "security",
    id: "6",
    title: "Web Security",
    content: [
      "HTTPS",
      "CORS",
      "Content Security Policy",
      "OWASP Security Risks",
    ],
  },
  {
    name: "package-managers",
    id: "7",
    title: "Package Managers",
    content: ["npm", "yarn"],
  },
  {
    name: "css-additional",
    id: "8",
    title: "CSS Preprocessors, Architecture, Modern CSS and Frameworks",
    content: [
      "BEM",
      "SASS",
      "Styled components",
      "CSS Modules",
      "Reactstrap",
      "Material UI",
      "Tailwind CSS",
      "Bootstrap",
    ],
  },
  {
    name: "build-tools",
    id: "9",
    title: "Build Tools",
    content: [
      "task runners - npm scripts",
      "module bundlers - webpack",
      "linters and formatters: prettier, ESLint",
    ],
  },
  {
    name: "react",
    id: "10",
    title: "React",
    content: [
      "React Elements",
      "React Fragments",
      "React Components",
      "React Props",
      "React Conditonals",
      "React Lists",
      "React Contex",
      "React Hooks",
    ],
  },
  {
    name: "web-components",
    id: "11",
    title: "Web Components",
    content: ["HTML Templates", "Custom Elements", "Shadow DOM"],
  },
];
export default articles;
